services:
  sdwu:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stable-diffusion
    volumes:
      - ./stable-diffusion-webui:/stable-diffusion-webui:z
      - venv:/home/diffustion/.local/lib/python3.9/site-packages:z
    ports:
      - "${SDWU_PORT}:7860"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${SDWU_PORT} || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    # networks:
    #   network:
    #     ipv4_address: $ADCM_HOST

# networks:
#   network:
#     driver: bridge
#     name: $NETW_NAME
#     ipam:
#       config:
#         - subnet: $NETW_ADDR
#           gateway: $NETW_GATE

volumes:
  venv:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/.local/lib/python3.9/site-packages/
